tryVital/vital-android

- VitalDevices/src/main/java/io/tryvital/vitaldevices/VitalDeviceManager.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/BloodPressureReader1810.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/GATTMeter.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/GlucoseMeter1808.kt
- app/src/main/java/io/tryvital/sample/ui/device/DeviceModel.kt
1. Align with iOS SDK API
* `DevicesManager` returns `GlucoseMeter` and `BloodPressureReader` objects, each of which offer `pair()` and `read()`.
* Removed `DevicesManager.pair()`.
* `read()` now attempts to pair with the BLE meter if the device hasn't already done so.
2. `pair()` and `read()` are now suspend (async) functions, since they either return one value or throw an exception.
4. Improved error propagation where all cases of the underlying BleManager request failure now throws a `BluetoothError` exception. Some of these previously are eaten up silently.
5. We now proactively disconnect after successfully reading samples. Accu-Check for example seems to rely on disconnection as a cue to prompt "transfer completed" to users.
6. Fixed a scenario where corrupted system BLE device …
> [VIT-2798] Improve GATTMeter error handling and device compatibility

- VitalClient/src/main/java/io/tryvital/client/dependencies/Dependencies.kt
- VitalClient/src/main/java/io/tryvital/client/utils/ApiKeyInterceptor.kt
- VitalClient/src/main/java/io/tryvital/client/utils/GzipRequestInterceptor.kt
- VitalClient/src/main/java/io/tryvital/client/utils/VitalRequestInterceptor.kt
`GzipRequestInterceptor` attempts to Gzip every single requests. But only certain POST endpoints support Gzipped request.
* Renamed `GzipRequestInterceptor` to `VitalRequestInterceptor`.
* Prevent `VitalRequestInterceptor` from gzipping requests except for a subset of endpoints.
* `VitalRequestInterceptor` now injects the `x-vital-ios-sdk-version` header into all API requests (subject to change; added for development testing)
> [VIT-2862] Fix GZip request interceptor

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/Utils.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalPermissionRequestContract.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/PermissionOutcome.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/WritableVitalResource.kt
- app/src/main/java/io/tryvital/sample/ui/healthconnect/HealthConnectCard.kt
- app/src/main/java/io/tryvital/sample/ui/healthconnect/HealthConnectViewModel.kt
Create an Android equivalent of these two iOS SDK APIs:
* `VitalHealthKitClient.ask(readPermissions:writePermissions:)` where one can specify a set of VitalResource and a set of WritableVitalResource.
* `VitalHealthKitClient.hasAskedForPermission` given a VitalResource.
In order to support these two APIs:
* We now track the permission status in `SharedPreferences` of each `VitalResource` and `WritableVitalResource`.
* A permission check is scheduled every time VitalHealthConnectManager is initialised, so as to detect permission grants and revocations done outside the SDK host app (in Health Connect's app).
Note that the signature of the API is slightly different due to platform SDK design differences.
HealthKit permission requests are no different from a normal async method call. On the …
> [VIT-2857] HC Permission API for parity with iOS ask(read:write:).

- VitalClient/src/main/java/io/tryvital/client/dependencies/Dependencies.kt
- VitalClient/src/main/java/io/tryvital/client/services/LinkService.kt
- VitalClient/src/main/java/io/tryvital/client/services/UserService.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Link.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/ProviderSlug.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Sleep.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Summary.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Timeseries.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/User.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Workout.kt
- VitalClient/src/main/java/io/tryvital/client/userConnectedSources.kt
- VitalClient/src/test/java/io/tryvital/client/ActivityServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/BodyServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/ProfileServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/SleepServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/SummaryServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/UserServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/WorkoutServiceTest.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordUploader.kt
- app/src/main/java/io/tryvital/sample/ui/healthconnect/HealthConnectViewModel.kt
- app/src/main/java/io/tryvital/sample/ui/healthconnect/ReadDataCard.kt
* Introduce `ProviderSlug` and `ManualProviderSlug` enums.
* Update request method/models to use these enums.
* Move the connected source creation logic from VitalHealthConnect to VitalClient as `VitalClient.createConnectedSource`. The implementation is currently very basic (always calling the API). Work from VIT-2924 and VIT-2944 will eventually bring parity with iOS SDK.
* Updated all the tests and fixtures impacted by the changes.
> [VIT-2945] Introduce provider slugs & update request models

- VitalHealthConnect/build.gradle
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- build.gradle
I didn't fully understand how the sync work was managed when doing #29.
Now upon reviewing the whole process from the entry point `syncData()`, I noticed my assumption of the SyncData workers being permanently running in background like a daemon was incorrect (fooled by the use of `observeForever`).
Instead, these are more like one-off workers, that are enqueued every time we need to sync. So this PR aims at rectifying them.
1. The async `syncData()` method now waits until the whole sync process is completed for all the specified resources before  it returns.
* Same as the iOS SDK.
* Caller can cancel the sync. Alternatively, `close()`ing the VitalHealthConnectManager would also cancel the sync.
2. `syncData()` is now serialized; only one will be executed at any given time. Other …
> [VIT-2993] Refactor sync work management

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
When testing RN, I noticed that some sync statuses were missing.
Turns out that we are using `tryEmit(_:)`.
`tryEmit(_:)` attempts to immediately send the value, but fails gracefully if the subscribers are not ready. This is suitable when we need backpressure from API consumers, but not for SDK sync status.
To address this, we configure the SDK sync status `SharedFlow` to have unlimited buffering. This allows `tryEmit(_:)` to always succeed (like Swift `AsyncStream` with unlimited buffering), since it can always write into the buffer, irrespective to the readiness of subscribers.
The buffer is designed to gradually shrunk as the subscribers drain from it (IIRC linked list underneath). So memory leak is not a concern.
https://github.com/tryVital/vital-android/blob/3512725ed4e5846e7630714120 …
> [VIT-2998] Sync Statuses are dropped instead of buffered for slow subscribers.

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthAutoStarter.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- app/src/main/java/io/tryvital/sample/ui/healthconnect/HealthConnectCard.kt
- app/src/main/java/io/tryvital/sample/ui/healthconnect/HealthConnectViewModel.kt
A convenient way to either open Health Connect for permission settings, or open Play Store if Health Connect is not yet been installed.
Also make sure VitalHealthConnectManager proactively bails itself out whenever it finds the HC SDK being unavailable. 
(iOS party ~= `x-apple-health://`...)
> [VIT-3030] Convenience to open Health Connect or Play Store if uninstalled

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/processChangesResponse.kt
Introduce `processChangesResponse` as a generic helper function for all VitalResources to extract their records of interests, and post-process them into the internal Vital SDK raw schema (ProcessedResourceData).
> VIT-3128: Generic HC ChangesResponse processing

- VitalClient/src/main/java/io/tryvital/client/services/VitalsService.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/ProviderSlug.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Timeseries.kt
- VitalClient/src/main/java/io/tryvital/client/utils/enum.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/processedresource/ProcessedResourceData.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordProcessor.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordUploader.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/UploadAllDataWorker.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/UploadChangesWorker.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/uploadResources.kt
Create a generic `uploadResources` helper function which accepts any Vital SDK raw schema (`ProcessedResourceData`) and uploads them to Vital's data ingestion API endpoints.
This PR also refactored most timeseries sample upload API to be generically accepting resource type + a list of QuantitySample, in order to simplify the implementation and not requiring a new method for each odd resource type.
> VIT-3743: Generic VitalResource upload process

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/processedresource/ProcessedResourceData.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordUploader.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncWorker.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/uploadResources.kt
* Mark uploads with historical vs daily stage correctly
* Merge all `ProcessedResourceData`s in the historical stage into one instance chronologically, and do only one upload (the merged version) like vital-ios. Descope SDK-side chunking for now, which needs to be properly designed to deal with edge cases, etc.
> VIT-3764: Send historical stage in one big upload

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncWorker.kt
Integrate the new ResourceSyncWorker into the HC SDK Client.
The new process:
1. We get the list of resources with read permission granted
2. We spawn a `ResourceSyncWorker` for each of these resources.
3. We wait for all the spawned workers to complete.
> VIT-2854: Enable ResourceSyncWorker

- VitalClient/src/main/java/io/tryvital/client/Configuration.kt
- VitalClient/src/main/java/io/tryvital/client/VitalClient.kt
- VitalClient/src/main/java/io/tryvital/client/dependencies/Dependencies.kt
- VitalClient/src/main/java/io/tryvital/client/utils/ApiKeyInterceptor.kt
- VitalClient/src/test/java/io/tryvital/client/ActivityServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/BodyServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/LinkServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/ProfileServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/SleepServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/SummaryServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/TestkitServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/UserServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/VitalsServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/WorkoutServiceTest.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncWorker.kt
- app/src/main/java/io/tryvital/sample/VitalApp.kt
- app/src/main/java/io/tryvital/sample/ui/healthconnect/HealthConnectViewModel.kt
Singletonize both VitalClient and VitalHealthConnectClient:
* VitalClient.getOrCreate(android.Context)
* VitalHealthConnectClient.getOrCreate(android.Context)
Passing in the Android Application Context is a standard singleton pattern on Android, e.g., [WorkManager.getInstance](https://developer.android.com/reference/androidx/work/WorkManager#getInstance(android.content.Context))
> VIT-2859: Singletonize the SDK

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/types.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncStarter.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncWorker.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/tryvital/sample/VitalSyncNotificationBuilder.kt
Upon further testing, we cannot upgrade our worker to be a Foreground Service when the app has entered background.
This means ideally we should start the Foreground Service status once (when the app is in foreground), and have the status lasting until ALL the resources requested have run to completion or failure.
This PR introduced `ResourceSyncStarter` as such worker (that manages the individual resource workers).
* It accepts a `Set<VitalResource>`, i.e. resources that need to be synced, as input.
* It calls `setForeground` before any work begins.
* It then spawns a worker for a resource, and waits for its completion before moving onto the next one.
* There is still room for optimisation as well, e.g., we should prioritise syncing historical stage first and then failed resources next …
> VIT-3963: Start Foreground Service only once for each batch of requested resources

- .idea/kotlinc.xml
- .idea/misc.xml
- VitalDevices/src/main/java/io/tryvital/vitaldevices/VitalDeviceManager.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/Libre1Reader.kt
- app/src/main/java/io/tryvital/sample/ui/device/DeviceModel.kt
- app/src/main/java/io/tryvital/sample/ui/device/DeviceScreen.kt
* Proactively check for BLE/NFC permissions and throw PermissionMissing when they are absent.
* Add a progress indicator and a Cancel button to the Device Example screen when a `read()` call is in progress.
> VIT-4348: More proactive DeviceManager permission checking

- .idea/misc.xml
- VitalClient/src/main/java/io/tryvital/client/Configuration.kt
- VitalClient/src/main/java/io/tryvital/client/VitalClient.kt
- VitalClient/src/main/java/io/tryvital/client/dependencies/Dependencies.kt
- VitalClient/src/main/java/io/tryvital/client/jwt/VitalJWTAuth.kt
- VitalClient/src/main/java/io/tryvital/client/utils/ApiKeyInterceptor.kt
- VitalClient/src/test/java/io/tryvital/client/ActivityServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/BodyServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/LinkServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/MockVitalJWTAuth.kt
- VitalClient/src/test/java/io/tryvital/client/ProfileServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/SleepServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/SummaryServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/UserServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/VitalsServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/WorkoutServiceTest.kt
- VitalClient/src/test/java/io/tryvital/client/testCommon.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- app/src/main/java/io/tryvital/sample/VitalApp.kt
- app/src/main/java/io/tryvital/sample/ui/healthconnect/HealthConnectViewModel.kt
Integrating VitalJWTAuth into VitalClient with the same approach as the integration in the iOS SDK.
Introduced `VitalClient.configure()`, `VitalClient.status` and `VitalClient.currentUserId` to mirror the iOS SDK.
Introduced `VitalClient.signIn` for sign-ins using Vital Sign-In Tokens + configuring the SDK into User JWT mode.
> VIT-4414: VitalJWTAuth - VitalClient integration

- VitalClient/src/main/java/io/tryvital/client/services/ControlPlaneService.kt
- VitalClient/src/main/java/io/tryvital/client/services/UserService.kt
These calls are not compatible with User JWT mode, and they are now exposed separately in a new location aka `ControlPlaneService` (created by `VitalClient.Companion.controlPlane`) that does not require SDK configuration.
> VIT-4470: Mark some UserService methods as deprecated

- VitalClient/src/main/java/io/tryvital/client/services/VitalClientExtension.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/ProviderSlug.kt
- app/src/main/java/io/tryvital/sample/ui/users/UsersViewModel.kt
1. Add typed OAuthProviderSlug
2. Introduce `linkOAuthProvider` to replace `linkUserWithOauthProvider`. The newer version no longer pretends to have caught all exceptions and return a `Result<Boolean>`. All exceptions are left to the caller to decide on the desirable way of handling.
> VIT-4551: Introduce VitalClient.linkOAuthProvider

- .idea/misc.xml
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/VitalResource.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordProcessor.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordReader.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncStarter.kt
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/tryvital/sample/PermissionsRationaleActivity.kt
Adapt the "Run sync as foreground service" feature to Android SDK Level 34 new restrictions on Foregorund Services.
Remove SleepStageRecord usage completely, since it is unsupported on Level 34+.
> VIT-5527: Android SDK Level 34 fixes

- VitalClient/src/main/java/io/tryvital/client/VitalClient.kt
- VitalClient/src/main/java/io/tryvital/client/utils/VitalRequestInterceptor.kt
In the unhappy path of `encryptedSharedPreferences`, we attempt to access the logger via implicit `this` (`this.vitalLogger`).
Avoid accessing `this` by obtaining the singleton via `VitalLogger.getOrCreate()` instead.
> CS1-80: Fix null pointer during Android SDK initialization

- .idea/misc.xml
- VitalClient/build.gradle
- VitalClient/consumer-rules.pro
- VitalClient/src/main/java/io/tryvital/client/Configuration.kt
- VitalClient/src/main/java/io/tryvital/client/Environment.kt
- VitalClient/src/main/java/io/tryvital/client/Region.kt
- VitalClient/src/main/java/io/tryvital/client/dependencies/Dependencies.kt
- VitalClient/src/main/java/io/tryvital/client/jwt/VitalJWTAuth.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Activity.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Body.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/CholesterolType.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/ControlPlane.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/DataStage.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Link.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Measurement.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Profile.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Sleep.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Summary.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Timeseries.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/User.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Workout.kt
- VitalHealthConnect/build.gradle
- VitalHealthConnect/consumer-rules.pro
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncWorker.kt
- app/build.gradle
- app/proguard-rules.pro
- app/src/main/java/io/tryvital/sample/AppSettingsStore.kt
- app/src/main/java/io/tryvital/sample/ui/settings/SettingsViewModel.kt
- build.gradle
Struggle to get Moshi reflective serialization working with R8 minification of Android Gradle Plugin 7.x, even though it works fine under AGP 8.x.
This PR migrates all JSON models to use Moshi codegen serialization, and removes the dependency on `moshi-kotlin` and `kotlin-reflect`.
Tested with R8 minification with both AGP 7.x and 8.x.
> CS1-95: Android: Migrate serialization from reflection to codegen

- .idea/misc.xml
- VitalClient/src/main/java/io/tryvital/client/VitalClient.kt
- VitalClient/src/main/java/io/tryvital/client/userConnectedSources.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/Utils.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- app/src/main/java/io/tryvital/sample/ui/healthconnect/HealthConnectCard.kt
- app/src/main/java/io/tryvital/sample/ui/healthconnect/HealthConnectViewModel.kt
Introduce `VitalHealthConnectManager.pauseSynchronization` which can pause synchronisation without having to reset the SDK via `cleanUp()`.
This will also auto-trigger a sync on unpause.
> CS1-120: Ability to Pause Health Connect Synchronization

- VitalClient/src/main/java/io/tryvital/client/VitalClient.kt
- VitalClient/src/main/java/io/tryvital/client/jwt/VitalJWTAuth.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- app/src/main/java/io/tryvital/sample/VitalSDKInitializer.kt
- app/src/main/java/io/tryvital/sample/ui/settings/SettingsViewModel.kt
* Fixed broken parsing of token refresh error response. `FirebaseTokenRefreshErrorResponse` should be used instead of `FirebaseTokenRefreshError`.
* If the signed-in user is deleted, the SDK now self-resets as if `VitalHealthConnectManager.cleanUp()` is called.
* Resetting the Core SDK also cancels the Health SDK data sync.
> VIT-5856: Improve SDK reset behaviours

- VitalClient/src/main/java/io/tryvital/client/VitalClient.kt
- VitalClient/src/main/java/io/tryvital/client/utils/logger.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- app/src/main/java/io/tryvital/sample/ui/settings/SettingsViewModel.kt
It is reasonable to expect that signOut might at some point involve some asynchronous operations.
So mark it as a suspend function even though we do not make use of it currently.
> VIT-5856: Future proof signOut() as a suspend function

- VitalHealthConnect/build.gradle
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/SyncBroadcastReceiver.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/Utils.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/backgroundSync.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/processLifecycleObserver.kt
- build.gradle
The SDK currently only automatically sync on process (app) recreation, which is a fairly low frequency event unless the user constantly force-closes the app.
Adopt `ProcessLifecycleOwner` so that we can bind the SDK to the ON_START event, which happens every time the user switches back to the app.
> VIT-6004: Background Sync on app resume

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalPermissionRequestContract.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/backgroundSync.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncStarter.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/SyncOnExactAlarmService.kt
* Reduce auto-sync trigger throttle from 10 minutes to 2 minute. That is, if a user reopens the app within 1 minute from the last sync, we skip the auto-sync.
* Remove the mitigation of strict rate limits added during Android 14 early betas, since it appears to have been relaxed in subsequent beta & GA releases.
* `syncData()` now consults `WorkManager` for any active sync worker. If one is found, it waits until their completion, rather than spawning new work.
* Auto-sync triggers now all depend on `ExistingWorkPolicy.KEEP` to avoid spawning more work.
* Improve `ask()` to reliably fire sync on non-interactive permission grants, as well as interactive grants as reported by the Health Connect Intent.
* Fix `VitalHealthConnectManager.status` emitting lots of duplicated sync statuses.
> VIT-6019: Tune auto-sync behaviour after more testing

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/SyncNotificationBuilder.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/Utils.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/VitalResource.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncWorker.kt
While we handle missing permissions gracefully when doing aggregations for Activity and Workouts, we did not do that when creating changesToken.
This caused ChangesTokenRequest to fail, in cases where:
* A user has not granted permissions for resources aggregating from multiple Record types (e.g. Activity); or
* A Vital customer did not declare usage of all data types (so user cannot grant it to begin with).
This PR does a few changes:
* We now filter the Record types by available read permission, before we make the `ChangesTokenRequest`.
* We now track the set of record types we used to request the changesToken.
* We now detect the scenario where the set of record types we monitor can change as a result of new read permissions being granted. We previously ignore this scenario.
Also fix …
> VIT-6034: Gracefully handle missing permission when generating Health Connect changes token

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/processedresource/ProcessedResourceData.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordUploader.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncWorker.kt
We unconditionally skip some upload POST requests when there is no data. This breaks historical.data.* event, which relies on an empty POST request being made by SDKs to signal the end of the historical stage.
> VIT-6150: Android: No historical.data.* event when no data

- VitalClient/src/main/java/io/tryvital/client/dependencies/Dependencies.kt
- VitalClient/src/main/java/io/tryvital/client/services/LinkService.kt
- VitalClient/src/main/java/io/tryvital/client/services/VitalClientExtension.kt
- VitalClient/src/main/java/io/tryvital/client/services/VitalPrivateService.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Link.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/vitalPrivate.kt
- VitalClient/src/main/java/io/tryvital/client/userConnectedSources.kt
- VitalClient/src/test/java/io/tryvital/client/LinkServiceTest.kt
Changes:
* Link Password Provider & Link Email Provider typing
* Move manual provider creation to the VitalPrivateService namespace.
Addition:
* Complete Password Provider MFA
> VIT-6624: Catch up with all API deprecations Pt.2

- VitalClient/src/main/java/io/tryvital/client/VitalClient.kt
- VitalClient/src/main/java/io/tryvital/client/userConnectedSources.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncWorker.kt
Remove:
* All deprecated SDK methods.
Move:
* VitalClient: instance method `checkUserId()` -> class method `checkUserId()`
> VIT-6624: Catch up with all API deprecations Pt.4

- VitalClient/src/main/java/io/tryvital/client/dependencies/Dependencies.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/vitalPrivate.kt
- VitalClient/src/main/java/io/tryvital/client/utils/InstantJsonAdapter.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/Utils.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/LocalSyncState.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/LocalSyncStateManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncStarter.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncWorker.kt
Mirror iOS SDK LocalSyncState + SyncInstruction + stage-less `/sdk_sync_state`, introduced in https://github.com/tryVital/vital-ios/pull/136
Also use Instant instead of Date in places being touched.
> VIT-6632: Caching SDK Sync State

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordProcessor.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncWorker.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/processChangesResponse.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/readResource.kt
Align Android SDK behaviour with iOS, where per-device activity timeseries is sent only if the team opts into the `sdk_per_device_activity_timeseries` feature flag.
> VIT-6636: Android: Honour the perDeviceActivityTs feature flag

- VitalClient/src/main/java/io/tryvital/client/services/TimeSeriesService.kt
- VitalClient/src/main/java/io/tryvital/client/services/VitalPrivateService.kt
- VitalClient/src/main/java/io/tryvital/client/userConnectedSources.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/Brand.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/BloodPressureReader1810.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/BloodPressureSample.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/GATTMeter.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/GATTMeterWithNoRACP.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/GlucoseMeter1808.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/Libre1Reader.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/postSamples.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordUploader.kt
- app/src/main/java/io/tryvital/sample/ui/device/DeviceModel.kt
Move timeseries POST methods to VitalPrivateService.
Mark `createConnectedSourceIfNotExist` as VitalPrivateApi.
Devices SDK would now try to auto-post glucose and blood pressure samples after reading them, if the Core SDK has signed-in with a user.
> VIT-6645: Device SDK auto-posting samples

- .github/workflows/android.yml
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalPermissionRequestContract.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/VitalResource.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/LocalSyncState.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncStarter.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/ResourceSyncWorker.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/processChangesResponse.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/workers/readResource.kt
- VitalHealthConnect/src/test/kotlin/io/tryvital/vitalhealthconnect/ResourceSyncStateTests.kt
- VitalHealthConnect/src/test/kotlin/io/tryvital/vitalhealthconnect/VitalResourceTests.kt
Health Connect uses a similar permission model as HealthKit. This means issues we encountered with HealthKit permission modelling are also applicable to Health Connect.
This PR ports the solutions over from the iOS SDK:
* HealthKitObjectTypeRequirements (now as `RecordTypeRequirements`)
* from https://github.com/tryVital/vital-ios/pull/120 and https://github.com/tryVital/vital-ios/pull/135
* RemappedVitalResource
* from https://github.com/tryVital/vital-ios/pull/132
> VIT-6651: Port the 3-pong permission mapping ruleset to Health Connect

- VitalClient/src/main/java/io/tryvital/client/userConnectedSources.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalPermissionRequestContract.kt
Proactively try to create a connected source, after the user has gone through the Health Connect permission flow successfully (i.e. did not cancel the prompt).
Also remove the `checkConnectedSource` caching (a persistent flag tracking if the CS has been created):
* In the Health Connect sync process, we would call this as part of the LocalSyncState revalidation logic, so it is already covered by the same 4-hour TTL.
* In Devices SDK, the reading happens somewhat sparingly in absence of BLE background scanning and auto-send support. So it is fine to have it calling the API without caching.
> VIT-6664: Android: Try to create connected source on successful Ask

- VitalClient/src/main/java/io/tryvital/client/services/VitalPrivateService.kt
- VitalClient/src/main/java/io/tryvital/client/services/data/Summary.kt
- VitalClient/src/test/java/io/tryvital/client/SummaryServiceTest.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/VitalDeviceManager.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/BloodPressureReader1810.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/GlucoseMeter1808.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/Libre1Reader.kt
- VitalDevices/src/main/java/io/tryvital/vitaldevices/devices/postSamples.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/processedresource/Activity.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/processedresource/BloodPressureSample.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/processedresource/ProcessedResourceData.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/processedresource/QuantitySample.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/processedresource/Sleep.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordUploader.kt
- app/src/main/java/io/tryvital/sample/ui/device/DeviceModel.kt
Align with iOS:
* QuantitySamplePayload -> LocalQuantitySample 
* BloodPressureSamplePayload -> LocalBloodPressureSample
Android specific:
* `*Payload` -> `Local*` e.g. SleepPayload -> LocalSleep
* (iOS modelled these differently where everything is nested under `ProcessedResourceData`. I don't see a strong need to change this on iOS)
The Local- prefix is here to avoid any clashes with Vital API response models, and also a very obvious cue of these Local- models being different from the API response models as well.
> VIT-6652: Rename all summary & timeseries POST endpoint models to Local*

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/HCActivitySummary.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/HCQuantitySample.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordAggregator.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordProcessor.kt
Request hourly activity totals from Health Connect using the `aggregateGroupByDuration` API.
One `AggregateGroupByDurationRequest` is made for the entire time range during we have discovered sample insertions.
https://developer.android.com/reference/kotlin/androidx/health/connect/client/request/AggregateGroupByDurationRequest
> VIT-6677: Request hourly activity totals from Health Connect

- VitalClient/src/main/java/io/tryvital/client/VitalClient.kt
- VitalClient/src/main/java/io/tryvital/client/jwt/VitalJWTAuth.kt
- VitalClient/src/main/java/io/tryvital/client/utils/logger.kt
Two issues:
1. Android Keystore not reliable across the whole Android OEM ecosystem, where some Googler suggested it is OEM firmware level issues. This in turn affects the reliability of a downstream component like `EncryptedSharedPreferences` in androidx-security-crypto.
* https://github.com/tink-crypto/tink/issues/535
* https://issuetracker.google.com/issues/176215143
2. Google decided to [deprecate the androidx-security-crypto library](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences).
This PR migrates away from androidx-security-crypto, and removes the usage of `EncryptedSharedPreferences`. Existing `EncryptedSharedPreferences` would be copied into a new `SharedPreferences` in a one-off migration.
> VIT-7220: Migrate away from androidx-security-crypto

- VitalClient/src/main/java/io/tryvital/client/utils/ApiKeyInterceptor.kt
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/records/RecordProcessor.kt
- app/src/main/java/io/tryvital/sample/AppSettingsStore.kt
- app/src/main/java/io/tryvital/sample/ui/settings/SettingsScreen.kt
- app/src/main/java/io/tryvital/sample/ui/settings/SettingsViewModel.kt
OkHttp deems all exceptions except `okio.IOException` to be "unexpected error" and subsequently crashes the app process.
This means within OkHttp request interceptors, application errors we introduced — e.g.`VitalJWTError` — must be wrapped in a `okio.IOException` subclass to be treated as recoverable soft error, and avoid causing a process crash.
---
Also fix the settings screen for not populating the current SDK user ID.
> VIT-7518: Exceptions thrown from OkHttp interceptor must be okio.IOException to be deemed recoverable

- VitalClient/build.gradle
- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/model/VitalResource.kt
- app/build.gradle
- build.gradle
VitalDevices and VitalHealthConnect already requires min SDK 26. There is no need for VitalCore to stay on min SDK 24. 
By moving VitalCore to min SDK 26, which exposes all Java 8 APIs, we can disable Core Library Desugaring entirely.
Note: This probably should result in a major version bump, since it would likely break the app project build.
> VIT-7773: Remove dependency on Android Core Library Desugaring

- VitalHealthConnect/src/main/java/io/tryvital/vitalhealthconnect/VitalHealthConnectManager.kt
`ProcessLifecycleOwner.addObserver` has a main-thread-only precondition.
Some customers use DI framework and cannot precisely control when they call `VitalHealthConnectManager.getOrCreate`. So they occasionally run into this main-thread-only precondition, due to the SDK's reliance on process lifecycle observer.
We now register the process lifecycle observer using `Dispatchers.Main.immediate`, which:
* If the caller is on the main thread, execute the lambda synchronously
* otherwise, schedule the lambda onto the main thread for async execution.
> VIT-7878: Always register SDK process lifecycle observer on the main thread
